services:
  backend: 
    build: ./backend
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    container_name: rewio_backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/rewio 
      - SECRET_KEY=01695553-c90c-745a-b76f-770d7b3dcb6d
    depends_on:
      db: 
        condition: service_healthy
    networks:
      - app-network
  
  frontend: 
    build: ./frontend
    container_name: rewio_frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BASE_URL=http://localhost:4000/api
    depends_on:
      - backend
    networks:
      - app-network

  db: 
    image: postgres:15
    container_name: rewio_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rewio 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  db_data:

networks:
  app-network: